### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by nashmuhandes** [nashmuhandes/io_export_gzdoom_md3#4]
### Issue 1:

'md3shader' object property doesn't work - the texture path does not get embedded

### Issue 2:

![Screenshot_Doom_20200809_152343](https://user-images.githubusercontent.com/4926156/89727302-d2af4a80-da55-11ea-9c1d-d913f132ecae.png)

Selecting multiple objects to export as a single MD3 produces a broken model

### Issue 3:

![Screenshot_Doom_20200809_152354](https://user-images.githubusercontent.com/4926156/89727311-e5c21a80-da55-11ea-95ce-3ac743c2685a.png)
![Untitled-1](https://user-images.githubusercontent.com/4926156/89727312-e9ee3800-da55-11ea-93d2-d61bbd142d60.png)

I am using the TiNA add-on to make multiple-separated meshes have seamless normals ([problem and solution is explained here - download to the TiNA add-on is one of the bottom answers](https://blender.stackexchange.com/questions/53749/normals-changed-after-separating-object-in-2-pieces)). The actual issue is that the seamless normals work in Blender but is not preserved when exporting to MD3.

Readily-runnable example file (includes .blend files)

Note that due to Issue 1, the models will be invisible (model texture paths aren't encoded upon export) - there are commented out Skin properties in the MODELDEF that can be used in the mean time.

[talontest.zip](https://github.com/nashmuhandes/io_export_gzdoom_md3/files/5046851/talontest.zip)

**Comment by Talon1024** [comment]
I just fixed issue 1. Now, the md3shader material property still takes precedence for each individual material, but it also uses the object md3shader property if the material md3shader property if it is given.

As for issue 2, how are you exporting the multi-object mesh? I just tried exporting a multi-object MD3 by having multiple objects selected, and it worked just fine for me, except it has seams like issue 3.

I'll look into issue 3 soon.

**Comment by nashmuhandes** [comment]
@Talon1024 for issue 2, I tried two things: manually selecting the several pieces together then pressing export, and also press A to select all. Both produce that broken model as seen in the image.

Can you perhaps send me a saved .blend file where it is confirmed that multiple selected meshes to export to a single .md3 doesn't get bugged?

**Comment by Talon1024** [comment]
Here's a blend file where exporting to GZDoom MD3 doesn't produce a broken model. It's not much different than your MultiObjectMonkey.blend, except I've packed your PNG texture: http://www.ciinet.org/kevin/myimages2/other/bugtests/MultiObjectMonkey.blend

Is your exporter up to date, and what version of Blender are you using?

**Comment by Talon1024** [comment]
I tried to make a fix to issue 2 and 3 on [this branch](https://github.com/nashmuhandes/io_export_gzdoom_md3/tree/fix/customNormals), since I assume you're using custom normals to make seamless normals between multiple objects, but I have no idea if I'm doing it properly.

My work on that branch is mostly based on what I've seen in the other scripts that are included with Blender.

**Comment by Talon1024** [comment]
Looks like triangulation in Blender 2.79 doesn't preserve custom normals.

**Comment by nashmuhandes** [comment]
@Talon1024 thanks for taking a look into these; will test your new commits this weekend (sorry, my free time is extremely limited on weekdays)

If any more issues crop up, I'll make new separate issues for them. Thanks again

**Comment by nashmuhandes** [comment]
@Talon1024 seems like the last good commit was https://github.com/nashmuhandes/io_export_gzdoom_md3/commit/0d53a3b3ede9a120aabd03afe37b4670bc8ccc61 - today I quickly tried exporting a simple door model and it produced a broken model.

We can probably ignore the issue about custom normals, although issue 2 should probably be looked at again more thoroughly. I will make a new issue to specifically tackle issue 2, but for now I'm just letting you know that maybe we should consider rolling back anything that's related to custom normals.
