### ISSUE TITLE
Archive the last working version for 2.79

### ISSUE THREAD

**Issue by nashmuhandes** [nashmuhandes/io_export_gzdoom_md3#6]
Hey @Talon1024 just a quick note, I see you've been making progress on updating the exporter to newer versions of Blender which is good, but before merging it into `master`, can you please preserve the last commit that will continue to work with 2.79?

I am still working on a few major standalones that must be finished with 2.79 and I won't be upgrading Blender for at least another 2 years.

**Comment by Talon1024** [comment]
I just set up the `blender_27` branch, for Blender 2.79 users, and possibly backporting improvements and fixes from the `neo_blender` branch.

**Comment by nashmuhandes** [comment]
Awesome!
